[[CURRENCIES]]
code="TestToken1"
issuer="GAUIZK25ARVPCWCT3R44HEU23TSFKMFTF4WNSXMQWKKX4LOJFRWEBOSV"
name="Your Name"
desc="Token 1 on Pi Testnet"
image="https://yourdomain.com/token1.png"

[[CURRENCIES]]
code=""
issuer="GAUIZK25ARVPCWCT3R44HEU23TSFKMFTF4WNSXMQWKKX4LOJFRWEBOSV"
name="Your Name"
desc="Token 2 on Pi Testnet"
image="https://yourdomain.com/token2.png"

[[CURRENCIES]]
code="TestToken3"
issuer="GAUIZK25ARVPCWCT3R44HEU23TSFKMFTF4WNSXMQWKKX4LOJFRWEBOSV"
name="Your Name"
desc="Token 3 on Pi Testnet"
image="https://yourdomain.com/token3.png"
